### ISSUE TITLE
auto-restart services on file changes

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#1]
As a developer editing an Exosphere application
I want that any changes I make to the source code gets loaded immediately into the runtime
So that I don't waste time manually restarting services all the time, or setting up service-specific auto-reloading.
- anytime a file in a service directory is created, updated, or deleted, `exo-run` restarts the respective service
- when a service is restarted, the logger outputs: `exo-run: restarting service '<service name>'`

**Comment by trushton** [comment]
This was taken care of in #165.
