### ISSUE TITLE
es6 service template isn't es6

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#109]
The es6 service template is in fact es5

**Comment by kevgo** [comment]
You mean https://github.com/Originate/exosphere-sdk/blob/master/templates/add-service/exoservice-es6/src/server.js and https://github.com/Originate/exosphere-sdk/blob/master/templates/add-service/exoservice-es6-mongodb/src/server.js? What is not ES6 about it?

**Comment by arekkas** [comment]
The module definition is not es6

**Comment by arekkas** [comment]
It should be:

```js
export const beforeAll = (done) => {
    // TODO: add asynchronous init code here, or delete the whole block
    done()
  },
```

**Comment by kevgo** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export says this isn't natively implemented yet. And Node 6.3 indeed doesn't support this natively at this point. I'd rather use the older version that is more compatible for now, and will upgrade to this syntax when it is more widely supported. In any case, these are just example templates to get app developers started. If somebody feels strongly about using ES6 exports, they can create their own template. Closing this for now, will review in a few months.

**Comment by arekkas** [comment]
Ha I didn't know that. Happens when you use webpack everywhere :)
