### ISSUE TITLE
sdk should support an ephermal infrastructure

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#123]
Right now, one has to install various tools to get exosphere working. Whilst npm and nodejs are common, 0mq header files are not. 0mq header files are required by many languages and are hard to compile on windows, as mingw, git, libsodium, ... is required.

As developers will most likely need databases and similar too, it would be good to do all of this in one place. There are various ways of achieving this (not an exclusive list)
- Use Docker with sophisticated Dockerfiles / docker-compose that support things like synching host and guest fs. 60% confident that this could work
- Use vagrant with virtualbox/hyper-v/... to encapsulate development environment (probably slow, large images and networking issues). it would work 100%, but suck 20% of the time
- Use vagrant backed by native docker (osx, win, linux) to have a uniform infrastructure (e.g. 1 mysql image, 2 development images, 1 exocom image, ...). no idea how good this will work

**Comment by kevgo** [comment]
I like the direction of using Docker. Exosphere should use Docker to provide as many dependencies as possible. We could leverage some middleware like Vagrant or Compose for orchestration if it fits.

**Comment by kevgo** [comment]
Resolved by the switch to Docker
