### ISSUE TITLE
Add deployment to DockerHub to "exo deploy"

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#160]
- when running "exo deploy", it packs up all services in an application into Docker files and pushes them to DockerHub
- if the service already exists on DockerHub, does nothing
- the DockerHub image name is "originate/exo-<service-name>-<version>"
- the repo for "exo-deploy" is https://github.com/Originate/exo-deploy

FYI later this command will also set up infrastructure on AWS, this is not part of this ticket.

**Comment by trushton** [comment]
@kevgo Now that we have a more clear vision of how the exo commands will be working with Docker, I think we should revise this issue. The first thing that comes to mind is that only services that the user is indicated as author of in `service.yml` will be deployable to DockerHub. From this, we will either need the user's Docker username to match to services for deploying them, or we simply attempt to push all services, but only ones that the user is logged in as author to will succeed. Additionally, we can incorporate the step of logging into Docker as part of this command, or just require that the user has done that beforehand.

**Comment by kevgo** [comment]
We shouldn't try to publish all images and then see a bunch of failures. Can we do something like this:
- make sure the user is logged into Docker. If not, assist the user in logging in. This could be aborting the script and showing an error message saying "Please run 'docker login' and re-run this command".
- once the user is logged in, determine the Docker username of the user
- with the Docker username, determine which images on Dockerhub the user can publish
- determine which services of the current app are in that list of publishable images. These are the service that the user can publish.
- only publish those images

**Comment by hugobho** [comment]
Pushing to DockerHub has been addressed. I have created a new issue to prompt the user to login to DockerHub before images are pushed.
