### ISSUE TITLE
exo create: create services inside Docker images

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#161]
As an application developer creating a new micro-service
I want to be able to create it on top of an existing Docker image
So that I am not slowed down with setting the service up on my machine first and then adding a Docker image later.
- running "exo add" creates the code base and a Docker file for the service
- the Docker image is based on base images that have the language runtime installed

**Comment by kevgo** [comment]
@alexdavid please review this ticket and make sure it makes sense

**Comment by alexdavid** [comment]
I'm confused what this ticket means. Do you mean you just want different base images created for every stack?

**Comment by kevgo** [comment]
I was thinking if somebody wants to create a Node micro-service, the "exo add" command automatically sets up the Docker image to run the service. This image is based on a Docker image that already has Node installed.

**Comment by trushton** [comment]
This was implemented with the move to Webpack, however only for Node, as all of our templates are only for node based micro-services.
