### ISSUE TITLE
ExoRelay stops abruptly on 'publish'

### ISSUE THREAD

**Issue by hugobho** [Originate/exosphere-sdk#172]
The o-tools `publish` command stops each time it reaches the `bin/spec` step. This has been happening on multiple machines but only for the ExoRelay repo. Does it have something to do with line 3 in the `bin/spec` script of ExoRelay:

`killall node 2> /dev/null`?

@kevgo

**Comment by hugobho** [comment]
@kevgo

**Comment by kevgo** [comment]
Yes, please remove this line from `bin/spec`.
