### ISSUE TITLE
`exo version` is not a command

### ISSUE THREAD

**Issue by alexdavid** [Originate/exosphere-sdk#174]
Tutorial prompts users to run `exo version` to test to see if exo sdk is successfully installed but it is not a command

**Comment by martinjaime** [comment]
@kevgo, should this have it's own repository, or just a condition on the same exosphere-sdk repository?

**Comment by kevgo** [comment]
Since this needs to read the `package.json` of the `exosphere-sdk` repo, it needs to live in that repo.
