### ISSUE TITLE
Read service.yml from service Docker images (exo-run)

### ISSUE THREAD

**Issue by trushton** [Originate/exosphere-sdk#190]
Exo-run should read `service.yml` data for each service directly from the Docker image that will be used to run the service. This way, the developer does not additionally need to have a copy of the code-base for every service that they use on their machine.

**Comment by kevgo** [comment]
@alexdavid and I were thinking about the best way to do that. I think our solution was to standardize the location in which that file needs to be. Then `exo-run` can simply run `cat /var/app/service.yml` in Docker to get its content.

Please chime in with better ideas.

**Comment by trushton** [comment]
Thats the idea I had, and I gave it a shot, the command `docker run #{image} cat service.yml` works as long as `service.yml` is at the root of the services directory `/usr/src/#{service}` in the docker image. The only issue I see with this is that to run the `cat` command on the image in the first place, we need the images author field, which we get from `service.yml`

I was thinking that since we have the auto-restart feature working for `exo-run`, and `exo-deploy` pushes changed images to dockerhub before deploying to AWS, could we list the Docker author/image as a field for the service in application.yml alongside (or replacing) the location field?

**Comment by hugobho** [comment]
Isn't the idea that in `application.yml` we point to a service's location, which will either be on in your application directory or DockerHub (or GitHub too?). In all cases we should be able to access the `service.yml` files. A service in the application directory is easy, we just do what we've done before. I'm assuming if we're running a reusable service on DockerHub, the `location` field in `application.yml` should point directly to that image on DockerHub, which would be its full name (`author/image`). I'm not sure what this would look like with a service location pointing to GitHub, though.

Regardless we should have enough information from the `location` fields in `application.yml` to extract the `service.yml` file from each service right?

**Comment by trushton** [comment]
Yes, that should be enough information for what we need. I see the cleanest way of doing this being that we could have a docker field with the `author/image`, and a github field pointing to the repo online. The only case I can think of that we would additionally want an actual "location" field pointing somewhere locally, would be if we wanted to test our applications NOT running inside of docker, which I'm not sure is something we shall be accounting for.

**Comment by hugobho** [comment]
Do you mean services not running inside Docker?

For services that users are actively developing those files would have to exist locally, no? It's only for  existing services on the 'service store' where we can point to the docker image instead of a local dir. Even if the `location` field points to a local directory we would still build it and run it as a docker image.

**Comment by trushton** [comment]
Actually we should be able to point to docker images even with services that are actively being developed, a docker image is still built for them when running `exo-setup` and that could then be used when doing `exo-run`. By *pointing to* the docker images, I simply mean that we give it the `author/image-name`, not the actual web address. If you attempt to run a docker image and you don't have it locally already, then it will pull the docker image automatically from dockerhub.

**Comment by alexdavid** [comment]
If we want to make this less opinionated we could say your docker image must have a `get-config` command that returns the configuration data as JSON or something. Then we could bake that into our exosphere base image

**Comment by kevgo** [comment]
We discussed this a bit more and decided to go with the file in a certain path. Advantages:
- when putting the code into `/var/app`, no extra stuff like a binary is necessary, it just works
- when putting the code in another directory, all that's needed is a symlink in `/var/app` to the service.yml file

**Comment by alexdavid** [comment]
I agree this is simpler and probably the best course of action for now. But let me play devil's advocate for a moment...

* A binary is a cleaner separation of what's inside docker and exosphere. Docker's run API takes in a binary to run. `docker run users-service get-config` vs `docker run users-service cat /var/app/service.yml` By running something like `cat /var/app/service.yml` you are assuming that the docker image has `cat` (I know cat is standard POSIX, so not a technical issue, just from a architecture perspective).
* I think configuration data passed from docker to exosphere should use a wire format like JSON. If a user wants to use exosphere to deploy some generic service who's configuration is defined in a non-yaml file this should be possible. It's also analogous to the docker APIs which are all JSON. This could be a technical issue if the yaml parser we use outside of docker is different from the yaml file used inside. There's only one way to describe a JSON object.
* It  scales better if we need to expose other things not specified in service.yml. Either additional configuration data that doesn't make sense to put in there or data that can be dynamically collected at runtime could be exposed through another binary. (Perhaps a `docker exec [container-id] get-cpu-load`)?

Some cons though are that docker containers not using our exosphere base image will need to re-implement these

Although I do think this adds an extra layer of complexity that we probably don't need right now so I'm ok leaving it how it is.

**Comment by kevgo** [comment]
All very good points @alexdavid. Maybe we extend exoservice with a "print-configuration" command to print out its configuration as JSON. This config includes data from the config file and command-line switches. And YML haters can use other formats for the config file. All that's needed is to add a bash script called "get-config" to the exoservice-js base image, which calls "exoservice print-configuration".
