### ISSUE TITLE
Install/test ExoCom via WebPack

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#201]
As an Exosphere developer
I want to run/test all different code bases that make up the SDK together
So that I can develop and release changes in multiple code bases at the same time.

Rules
- running the tests uses the local code bases 
- publishing a new version uses the local code bases

Notes
- here is the build script from YARN: https://github.com/yarnpkg/yarn/blob/master/scripts/build-webpack.js

**Comment by trushton** [comment]
This is now being tracked by [Originate/exosphere#19](https://github.com/Originate/exosphere/issues/19)
