### ISSUE TITLE
ExoCom: Show response time of service

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#30]
As a service developer
I want to see the response time of my service
So that I know how well it performs at all times.
- if a message is a reply, i.e. contains a `responseTo` field, ExoCom displays the response time of the service, i.e. the time difference between when the original message was sent to the service and when its answer was received

blocked on #29

**Comment by martinjaime** [comment]
Addressed by Originate/exocom-dev#14.
