### ISSUE TITLE
exo-run: end the runner when a service ends

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#33]
As an application developer testing my application in dev mode
I want the whole application to stop when one of my services crashes
So that I can investigate the issue without traces being removed by further activity.
- When a service crashes, the whole application runner ends
- the user sees a stack trace of the crash in the service

**Comment by kevgo** [comment]
Hey @martinjaime, did you get to work on this issue already? If not, I'll assign it to Helen.

**Comment by martinjaime** [comment]
No, I did not start any work on this.
