### ISSUE TITLE
exo add: better error message when running in a non-Exosphere directory

### ISSUE THREAD

**Issue by kevgo** [Originate/exosphere-sdk#67]
As an application developer accidentally running `exo add service` in a directory that doesn't contain an Exosphere application
I want to be given a friendly error message explaining that I have to run this command within an Exosphere application's directory
So that I recognize my mistake and know how to run the command properly.

Rules:
- when running "exo add service" in a directory that doesn't contain a file "application.yml",
  the command prints: "Error: application.yml not found. Please run this command in the root directory of an Exosphere application."

**Comment by martinjaime** [comment]
Closed by 78a8bb63271c18ec321da9771c354fe7d6ed0781
